[project]
name = "SAM-2"
version = "1.0"
description = "SAM2 (fork)"
readme = "README.md"
requires-python = ">=3.10"

[tool.setuptools]
packages = ["sam2"]

[build-system]
requires = [
    "setuptools>=61.0",
]
build-backend = "setuptools.build_meta"
